name: BendixAntiSpam
version: ${project.version}
main: dk.rasmusbendix.antispam.AntiSpam
api-version: 1.16
authors: [rasm945i, BenteBoi]
description: Prevents repetitive messages and spam
website: https://en.rasmusbendix.dk
commands:
  antispam:
    description: Base-command for the antispam plugin
    aliases: [aspam]